language: cpp
sudo: false

dist: trusty

env:
    - LLVM_CONFIG=llvm-config-3.9

compiler:
    - clang++-3.9
    - g++-5
git:
  depth: 1
addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-5
      - llvm-3.9-dev
      - clang-3.9
      - libz-dev

before_script:
  - cmake . -DLLVM_CONFIG=$(which ${LLVM_CONFIG})

script:
  - make -j2
  - make test
notifications:
    email: false
