language: cpp
sudo: true

dist: trusty

git:
  depth: 1

addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - libz-dev

env:
    matrix:
        - LLVM_VERSION=3.8 DG_TESTS_PTA=fs
        - LLVM_VERSION=3.8 DG_TESTS_PTA=fi
        - LLVM_VERSION=4.0 DG_TESTS_PTA=fs
        - LLVM_VERSION=4.0 DG_TESTS_PTA=fi
        - LLVM_VERSION=5.0 DG_TESTS_PTA=fs
        - LLVM_VERSION=5.0 DG_TESTS_PTA=fi

compiler:
    - 'clang++'
    - 'g++'
    - 'g++-5'

install:
  - git clone --depth 1 https://github.com/tomsik68/travis-llvm.git
  - cd travis-llvm
  - chmod +x travis-llvm.sh
  - ./travis-llvm.sh ${LLVM_VERSION}
  - cd ..

script:
  - cmake .
  - make -j2
  - cd tests
  - make
  - make test

notifications:
    email: false
