language: cpp
sudo: required

dist: trusty

git:
  depth: 1
addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-5
      - llvm-3.9-dev
      - clang-3.9
      - libz-dev

before_script:
  - sudo apt-get -yq --force-yes remove llvm-3.5-dev clang-3.5
  - cmake . -DCMAKE_CXX_COMPILER=clang++-3.9

script:
  - make -j2
  - make test
