language: cpp
sudo: false

dist: trusty

git:
  depth: 1
addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - gcc-5
      - cmake
      - llvm-3.9-dev
      - clang-3.9
      - libz-dev

before_script:
  - cmake .

script:
  - make -j2
  - make test
