language: cpp
sudo: true

dist: trusty

compiler:
    - clang++-4.0
    - g++-5

git:
  depth: 1

addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - g++-5
      - libz-dev

script:
  - git clone --depth 1 https://github.com/tomsik68/travis-llvm.git
  - cd travis-llvm
  - chmod +x travis-llvm.sh
  - ./travis-llvm.sh 4.0
  - cd ..
  - cmake .
  - make -j2
  - cd tests
  - make
  - make test

notifications:
    email: false
