language: cpp
sudo: true

dist: trusty

compiler:
    - clang++-4.0
    - g++-5

git:
  depth: 1

addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-5
      - libz-dev

before_script:
  - git clone --depth 1 https://github.com/tomsik68/travis-llvm.git
  - cd travis-llvm
  - ./travis-llvm.sh 4.0
  - cd ..
  - cmake .

script:
  - make -j2
  - cd test
  - make
  - make test

notifications:
    email: false
