language: cpp
sudo: false

dist: trusty

git:
  depth: 1
addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - llvm-dev
      - libz-dev

before_script:
  - cmake . -DCMAKE_CXX_COMPILER=g++-5

script:
  - make -j2
  - make test
